name: migration
description: SQL migrations for Jaguar ORM.
version: 2.1.1
homepage: https://jaguar-dart.github.io/
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  jaguar_query: ^2.1.6
  xml:

dev_dependencies:
  test: ^1.2.0
