name: jaguar_orm_gen
description: Generator for jaguar_orm
version: 2.2.30
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm
documentation:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  jaguar_query: #^2.2.9
    path: ../query
  jaguar_orm: #^2.2.7
    path: ../orm
  analyzer: ^1.5.0
  build: ^2.0.1
  logging: ^1.0.1
  source_gen: ^1.0.0
  meta: ^1.3.0
  collection: ^1.15.0-nullsafety.4

dependency_overrides:
  jaguar_orm:
    path: ../orm
  jaguar_query:
    path: ../query

dev_dependencies:
  test: ^1.17.1
  build_runner: ^2.0.1
  build_test: ^2.1.0
  collection: ^1.15.0
  path: ^1.8.0
