name: jaguar_orm_gen
description: Generator for jaguar_orm
version: 2.2.27
authors:
  - Ravi Teja Gudapati <tejainece@gmail.com>
  - Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar_query: ^2.2.8
  jaguar_orm:
    git:
      url: https://github.com/RnDity/jaguar_orm.git
      path: orm
      ref: upsert_and_generator_changes
  analyzer: ^0.36.0
  build: ^1.1.4
  source_gen: ^0.9.0
  logging: ^0.11.0
  meta: ^1.1.5

dev_dependencies:
  pedantic:
  test: ^1.3.0
  build_runner: ^1.5.0
  collection: ^1.14.10
  path: ^1.6.2
