name: jaguar_orm_gen
description: Generator for jaguar_orm
version: 2.2.30
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar_query: ^2.2.9
  jaguar_orm: ^2.2.7
    #path: ../orm
  analyzer: ^0.38.0
  build: ^1.2.2
  logging: ^0.11.3+2
  source_gen: ^0.9.4+6
  meta: ^1.1.8

dev_dependencies:
  test: ^1.9.4
  build_runner: ^1.7.2
  build_test: ^0.10.11
  collection: ^1.14.12
  path: ^1.6.4
