name: jaguar_query_postgresql
description: postgresql adapter for jaguar_query
version: 2.1.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  jaguar_query: # ^0.2.4
    path: ../query
  logging:
  postgresql2: ^0.3.4

dev_dependencies:
  test: ^1.0.0
