name: jaguar_orm
description: ORM
version: 0.0.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  jaguar_query:
    path: ../jaguar_query

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
