name: jaguar_query_example
description: Dialect neutral, fluent Dart DSL to build SQL/NoSQL queries
version: 2.2.9
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar_query:
    path: ../

dev_dependencies:
  jaguar_query_postgres:
    path: ../../postgres