name: jaguar_query
description: Dialect neutral, fluent Dart DSL to build SQL/NoSQL queries
version: 2.1.8
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm
documentation:

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  meta: ^1.1.5

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  jaguar_query_postgres:
    path: ../postgres
  jaguar_serializer: ^2.1.8
