name: jaguar_query
description: Dialect neutral, fluent Dart DSL to build SQL/NoSQL queries
version: 2.2.9
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm
# documentation:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.17.10
